{{- if not .Values.auth.existingSecret }}
{{- $anyCredential := or .Values.auth.credentials.elasticsearchPassword .Values.auth.credentials.elasticsearchApiKey .Values.auth.credentials.mcpApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elasticsearch-mcp-server.fullname" . }}
  labels:
    {{- include "elasticsearch-mcp-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.credentials.elasticsearchPassword }}
  {{ .Values.auth.existingSecretKeys.elasticsearchPassword }}: {{ .Values.auth.credentials.elasticsearchPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.credentials.elasticsearchApiKey }}
  {{ .Values.auth.existingSecretKeys.elasticsearchApiKey }}: {{ .Values.auth.credentials.elasticsearchApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.credentials.mcpApiKey }}
  {{ .Values.auth.existingSecretKeys.mcpApiKey }}: {{ .Values.auth.credentials.mcpApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
